language: scala

sudo: false

scala:
- "2.12.2"
- "2.11.12"

jdk:
- oraclejdk8

# build all PRs and only master branch and branches starting with either
# 'deploy-*', 'deploy/*', 'ci-*' or 'ci/*'
branches:
  only:
  - master
  - /^(?i:deploy)(-|\/).*$/
  - /^(?i:ci)(-|\/).*$/

# cache local ivy cache, but delete properties and lock files beforehand
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot

# if build is a pull request and origin branch starts with doc/ skip the build (successfully)
before_install:
- if [[ "$TRAVIS_PULL_REQUEST" != "false" && "$TRAVIS_PULL_REQUEST_BRANCH" == doc/* ]]; then exit 0; fi

# build script (sbt test and sbt run sampleapp.Main)
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport coverageAggregate codacyCoverage
- sbt ++$TRAVIS_SCALA_VERSION "sampleapp/runMain de.up.hpi.informationsystems.sampleapp.Main"

env:
  global:
    secure: nbdrMuGFLucqjkSxl9nJt2pX4SJcrG8caleW/7cuFKBT4/ZFgoI4eO98Rr0SRPZkQwqF3pSTzDg9nIr98anNWUEROSfV2RqMBFdxduUofzHomeUbCIRlJPFY9O67GZ8Ex9eREiKhlET2y6dgKP3FBt9eaRm2rRg0kE4qzADchgKl2VZ1wWDiskno5c2guT/aifXcoL/piRw9q+vz1zD5xao1iybkL3a2GZG9dysjrcfdDuZhqbXxjoWkqeqTLg52j5iJk9BKxY6DabNR0P3xsrCGg5Di1PN8+O5ty55cjCI96vydLsiADIQfUPjvIqZTEmEViyfIX22G+CTHrr9wY2ZT9kmXpZ7EihdXSlMVrhQZbsuAZ2rsG/bpfQGexDWGO+r5IK3/q/1hSJrkmPXwZEyDlrYcKUnEoZ/P7BaM+grBgPfCirHwi5IcUL1fX50c4Ailb8xVeDUaanc7vEUJa/iVWH/uZ3cdKmZO+N/9B6vF2LCcitQNtiJy9kIjjrislHMOuJv/QbOxSEo0JZB3kZXWQJdGC5UJthqK5nkdnFLZ6NpUnscHh8S36XvGd3cRaF8QvHFTn8NHXkoZlkggaOl2aaOWjH2QVrmvmvXKHXKYwRhQSubXQ7YpQeQTQQYF7ZSGHQvQrU+gVWkj+mE1f8waz5cME+SZpcsUewnrtqI=
