language: scala

sudo: false

scala:
  - "2.12.2"
  - "2.11.12"

jdk:
  - oraclejdk8

# build all PRs and only master branch and branchs starting with either
# 'deploy-*', 'deploy/*', 'ci-*' or 'ci/*'
branches:
  only:
    - master
    - /^(?i:deploy)(-|\/).*$/
    - /^(?i:ci)(-|\/).*$/

# cache local ivy cache, but delete properties and lock files beforehand
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

# build script (sbt test)
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
