language: scala

sudo: false

scala:
- "2.12.2"
- "2.11.12"

jdk:
- oraclejdk8

# build all PRs and only master branch and branches starting with either
# 'deploy-*', 'deploy/*', 'ci-*' or 'ci/*'
branches:
  only:
  - master
  - /^(?i:deploy)(-|\/).*$/
  - /^(?i:ci)(-|\/).*$/

# cache local ivy cache, but delete properties and lock files beforehand
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot

# if build is a pull request and origin branch starts with doc/ skip the build (successfully)
before_install:
- if [[ "$TRAVIS_PULL_REQUEST" != "false" && "$TRAVIS_PULL_REQUEST_BRANCH" == doc/* ]]; then exit 0; fi

# build script (sbt test and sbt run sampleapp.Main)
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport coverageAggregate codacyCoverage
- sbt ++$TRAVIS_SCALA_VERSION "sampleapp/runMain de.up.hpi.informationsystems.sampleapp.Main"

env:
  global:
    secure: ak3YYs7IYs0XGOrIthG5OH6gNXZYP60d1laAK8y9fHrOmtm87Nk7HX3+MsXZnkQb3J6OrBbidh5IZc7eIVzIBvs5ZWDLIDFHILw4yt1h1X3dGkwnfoiofWFXkBOM4/m4RdQG1PLqVnA9HJFofp4XepXK44rZ4hL+yB4Qe7CvCX7PhmjPplSXVXCpfqR7aeIqKr8RmhblpPJZMrRzQBPcYJTUWe1b5y9IhFCaniROtLAehZgtYu7Kj4aCAcCvnkdBbIOd5Jleqf6R1i19FLhNyexbEE50lseXX6aybvZzBKMlIeyW/TDB1AdjMpCCNIzmbw2Ted/HAFzHkqppmFfqpBXtV+Vh6HJMciOY+wxRIlkbHwm+uTmCpXzrdd5rgmgRFxPwCozmnCf58RljV9BQ6SNsFq3lnq6sNGIlkgjvsvPSL35DrnGdauQmTiA4s2ZSMiQC0uyLVRyFmMN8yKDpkgzuUyzm7BCExa0g/ol3MqJh8VIG8oIFefKEWMKlRVSG7zFW/poLvr2x37FmL7dqiGrKx5TqjIy4xIQxu+FmLmdd/CAnKQ0Pj7lSOLVqiP4eRnQv4XLPopwic2xLBkoWSJDHYsKErSZkrEhE/HqYkqEbkKGv+hw1GmtaM7AyTrbGcuL2hXQatTIxi9lmZCnLjs2cG8PWGxp67xeCRSM5TFk=
